apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgA+/7bFcxEaiJZFOkRF2ljkHPfRACifXAIXoU7Y4csa0ZZizY9uo4K83ojMq7cZCBbLb8mD9CNUTCDKRqW4QabeMzoQ+8Ort3inOY/82OvTyqG39ZyWSZG9nlxZePsHv8tC2MGrDkB9udrMhyoqqRE9whJcobT2QM9olkqhNl8i8KF0aYZGRwWg6WvWD5gaAEZM3evb5htc+0XRaDNWTi1FziKpDQXmvY2jEMWylunEFafO6bnYWomZ/VMtwoLRLkyja00ES0BVrnOfjelkVe+T60bdrVvIe9y03+W3jUwgJICkPL791DO8zs3R56w2l15hbiKhcVGV+PYZHFB/akFKxvjL+1CXuSlWlHOOWCmFaRH4qTMgUwBPSSQx0s86Be7q4q4hDU9Qu/pTmAn0R4a+LOkKZdDE2MdCyq/9PTKuLrYBbpB09fXqZh/yyI+h3+zWUgAZEDzSliPzCX9ZDohQz4eB98zONAKq/a8cNVbhruTtw2cQnx8tNStsQXroBYOimwf6fo9ziMCX/k0nVfeX5a9jCoSUnkMQJOJDJppVgnWdlpcK1rFtOtpLPKL+CrHvC8xPJEH1K1Y2wO7XspyN5cV5vIY//X3rYC1RlHSS3h+vVmq3qXGb6u7sW2QUvRLdFC7t31wnXxYCiZazjNa6egyUvByFJwn9XiE2wyulIfN0h5dUnCdxC7vfY4bM2OD1PBryAGFkkxmhBADxReWDmMFXfA==
    secret-access-key: AgACz15ZD4kLQNB3n/KsdxCXxMPudwPOrMPBpUEA4Hmtx0iK1lSSccT/mdK6LnAJIqz/azS6Bm87V7hjb18LQa5slUlREaILZWvJof+gVHWFfn0bZWRM9+0MT2NoGICuD9TPCUUaA0clsrb5G9JNGmDZWtp65F6+0YzACkydAXmIKH5MjCuKgrOdjjrJWaFLxGLAqkZYoC1nis+7/H+rO+jCbbT5EgPgITdIIXEavK3YuuXm/Gn1HzR0s3Jvk/XpwbN4HMDwM0wKK48h13tw6nzSkxuuboeKIxDJQqPr78ojoTE7eGWHoSuF+kBdUYI3N+3KR8r+BmzNMKYvDZHSFE5QwTIwLElFWlp+uPJEfAm8Eem8YZzAWrs0zE5Z8qvaPm3YlXw3EUYcx/g+ie1jfJP/ckvSTX/hmUsw/0lumvlfCwNdQ+efpz8HRFM28uHi535o1B0tIPoxQibwFCOhIw9ogjSUHg/hHp/p53YZvgpnuSeO+KcP1I5DMSzE9edmPGgzTja0tCMB3GjGEtIuTarmbCcdWH+YWcFJ6zD/gmzF/ZcaMYRXKSqRNWpjxdm7Uj+oSOLYEqnXczS0kTBKa+UI45t/8wZhMhnzGHitalpDpjFRxy9YgSX58C4LiObeqnQvI1GEzBvyehiQv3r7RI/T0l+PbTPvBJidrDEmCiI3k9UoWWrLJMblV8OGh60xoesW+7hEDAP4oBX1mBx1h+LbpEhjMCacSTVSSRz82i5t3g7uJjlrWuyc
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
    type: Opaque
