apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: external-dns
spec:
  encryptedData:
    access-key-id: AgC17/wf0olLHAZT+WOuyOUuuzeZHLRv8nYxXZgZZv0PpSPrhS9/0DpyNcHUr1pQaL5DyEu3ijlBmSaL5vrRmdZrkGVOLxDogv0Dp6d6x53MECQk48KFLDPl0GPsHlHEcX8zuuIvqWyqaP6bR+/KshfR/2N3RJ+OK4y/dOw/6F/UGsWKhSyOqBaJEj+Z60t90g6+fRIhTjCNnZo9hQpMZtEMF45kib2Ra+H/4JHRi8svvoVza7kEsfC7NSJ6o2iXywiXH99I7KJ09r+Snhe2vSZ1Z2XuUjrs3j+sEelPmZJ+0GgeNQ13DdFbUQWV9sycBxiRW5RBVIfBQb9vbBkkS8nWE/iveR2wTGuOdqDr/cDIWOeP0ahXU/+O3AUOvLZxuKLMe/2fIulSGaPRmwWHRXeF88geObrhECS8lsWyNZmg0PQ36qTEWZLJj6c9jpUoGxYhTxR5FvllrGh+FianNZFvGiXq/tmWJM+POouBGqKnChILKbJcbQFK59J5MwwASfg4FBRjdya1wchO1uGAdrM68r6h6sfYmIurwcek25fi82UjuOsoMqd/AvXi5Qol3x2TjxEvylEXWVJ3FikkxFkxijnu/85J+IkTlKNIschoIxMh5Qn0aEgZcO2+F5/Fbwy66pJPm+5gT7lmVrRYEO5kZFr1Z+tGVZIGhLY8M0a0/PWog8lwEl6k2jaA5ZHwhFZXkS4mZiDghvYYWXw0EsEsKvL3ZQ==
    secret-access-key: AgAwDKVnV5rk7CqbcrkFy37ciKUgxBx3kRcmO5wHQHpL4f4bV8fkWY1FLEkldiSoOGa4gaXVpqbox8zEDpowWXt7QKqVFrFxr1TOkteBW3PcaC7j9xDkPw75qj0Y81Mb2SGzSRumSRIJ/GgqQFg9uDp1QDWtgf2Wq5Jf0714ZDgOzApm8RtJ7jnLMikU1Za7cMmtg9AYsmXRwi+vyXzD5OE3pXd1FEM+QOuUh1iQ9FvXjLY5bIqRPinHRnjK9eOMD4gzfnriFHeu2Jvui435/Ph6uyXC74NebcsHIB25HoXRnzFyu8Dq8XJZzKW1r+xSsZnorgMBftV2EKZJhCgKT1VKPbyhnKITd7HJzK39lP/kFHeKBscbehgrEOHcJQBO6l4eAo2TJFn41mFIF0p8/fF6aIvPJwRq6SlYTjq6h19dLEBuW4WRPOMdA7njPx7+O9q1+LNtRCHkIVzIr3133zP3jfQF/+MIcuJM+npsVDoworQXiWTrMR4BqDjV69Q9TnUNMulrkCgq4oubrTNL3Gz96uVpRken/yGm41Dr4oHfD9YAFfqWh1GPWi7qwTod+sKVE6Jv2PZfylDNmoDzEJVDMJj+eAP1wLemESGNZn2UTnLgU7JFr2FanJ2wnovXZhihs5fqSw95jaYLDGxRdBLske76d66wCD7l2g2yOYGB/XPwQiyW0vMj3+zhqv/r/ilVuchjbksKmC/lwMvPrmPkMEb9p0YobngvFgAqfzNnyH9T2iWszw50
  template:
    metadata:
      name: route53-credentials
      namespace: external-dns
    type: Opaque
