apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ingress.yaml
  - cert-manager.yaml
  - dns-config.yaml
  - external-dns.yaml
  - sealed-secrets.yaml
  - cloudnative-pg.yaml
  - barman-cloud.yaml
  - recovery.yaml
  - monitoring.yaml
  - loki.yaml
  - tempo.yaml
  - alloy.yaml
  - observability-config.yaml
  - grafana.yaml
  - platform-access.yaml
  - taeria.yaml
