apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ingress.yaml
  - cert-manager.yaml
  - dns-config.yaml
  - external-dns.yaml
  - sealed-secrets.yaml
  - recovery.yaml
  - monitoring.yaml
  - grafana.yaml
