apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 91.2.3
    helm:
      releaseName: monitoring
      valuesObject:
        grafana:
          enabled: false
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 2
            podAntiAffinity: soft
            resources:
              requests: { cpu: 50m, memory: 128Mi }
              limits: { cpu: 300m, memory: 256Mi }
        kubeControllerManager: { enabled: false }
        kubeScheduler: { enabled: false }
        kubeEtcd: { enabled: false }
        kubeProxy: { enabled: false }
        prometheus:
          prometheusSpec:
            retention: 7d
            retentionSize: 25GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: [ReadWriteOnce]
                  resources:
                    requests:
                      storage: 30Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
