apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recovery
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/KAeHM/personal-cluster.git
    targetRevision: main
    path: platform/recovery
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
