apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: taeria
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  description: Recursos exclusivos do Taeria em produção
  sourceRepos:
    - git@github.com:KAeHM/taeria-infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: taeria-prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: LimitRange
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: batch
      kind: Job
    - group: bitnami.com
      kind: SealedSecret
    - group: barmancloud.cnpg.io
      kind: ObjectStore
    - group: monitoring.coreos.com
      kind: PrometheusRule
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: postgresql.cnpg.io
      kind: Cluster
    - group: postgresql.cnpg.io
      kind: Backup
    - group: postgresql.cnpg.io
      kind: ScheduledBackup
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taeria-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "51"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: taeria
  source:
    repoURL: git@github.com:KAeHM/taeria-infra.git
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: taeria-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
