apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.10.0
    helm:
      values: |
        controller:
          type: daemonset

        alloy:
          configMap:
            create: false
            name: alloy-config
            key: config.alloy
          extraPorts:
            - name: otlp-grpc
              port: 4317
              targetPort: 4317
              protocol: TCP
            - name: otlp-http
              port: 4318
              targetPort: 4318
              protocol: TCP

        service:
          enabled: true
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
