apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.0
    helm:
      values: |
        adminPassword: "admin"
        ingress:
          enabled: true
          ingressClassName: tailscale
          hosts:
            - grafana.tail412374.ts.net
          tls:
            - hosts:
                - grafana.tail412374.ts.net
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
