apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taeria
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KAeHM/personal-cluster
    targetRevision: master
    path: infra/taeria
  destination:
    server: https://kubernetes.default.svc
    namespace: taeria
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
